media: assets/img
content:
  - name: tools
    label: Tools
    type: collection
    path: '_tools'
    view:
      fields: [ title, tags, image-html ]
    fields:
      - name: layout
        label: Layout
        type: select
        options:
          values: [ tool, stack ]
      - name: tags
        label: Tags
        type: select
        options:
          values: [ design, development ]
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: link
        label: Link
        type: string
      - name: image-html
        label: Image HTML
        type: code
      - name: body
        label: Body
        type: rich-text
  - name: bookmarks
    label: Bookmarks
    type: collection
    path: '_bookmarks'
    view:
      fields: [ title, tags, date ]
    fields:
      - name: layout
        label: Layout
        type: select
        options:
          values: [ tool, stack ]
      - name: tags
        label: Tags
        type: select
        options:
          values: [ design, development ]
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: link
        label: Link
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text